name: jaxoptax
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.7.2=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.14=h5eee18b_0
  - pip=24.2=py311h06a4308_0
  - python=3.11.9=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=72.1.0=py311h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - tzdata=2024a=h04d1e81_0
  - wheel=0.43.0=py311h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.1.0
      - chex==0.1.86
      - etils==1.9.2
      - jax==0.4.31
      - jax-cuda12-pjrt==0.4.31
      - jax-cuda12-plugin==0.4.31
      - jaxlib==0.4.31
      - ml-dtypes==0.4.0
      - numpy==2.0.1
      - nvidia-cublas-cu12==12.6.0.22
      - nvidia-cuda-cupti-cu12==12.6.37
      - nvidia-cuda-nvcc-cu12==12.6.20
      - nvidia-cuda-runtime-cu12==12.6.37
      - nvidia-cudnn-cu12==9.3.0.75
      - nvidia-cufft-cu12==11.2.6.28
      - nvidia-cusolver-cu12==11.6.4.38
      - nvidia-cusparse-cu12==12.5.2.23
      - nvidia-nccl-cu12==2.22.3
      - nvidia-nvjitlink-cu12==12.6.20
      - opt-einsum==3.3.0
      - optax==0.2.3
      - scipy==1.14.0
      - toolz==0.12.1
      - typing-extensions==4.12.2
prefix: /PLEASE/SET/ME/TO/YOUR/CONDA/PATH/jaxoptax
